version: "3.8"

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    dns:
      - 192.168.182.128
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/etc/nginx/html
      - ./certs:/etc/nginx/certs
    networks:
      - single-node_default


networks:
  single-node_default:
    external: true
