filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/apache2/*.log
  fields:
    logtype: modsecurity
    service: waf
    environment: production
  fields_under_root: true
  multiline.pattern: '^\[[0-9]{2}\/[A-Za-z]{3}\/[0-9]{4}:'
  multiline.negate: true
  multiline.match: after

- type: log
  enabled: true
  paths:
    - /var/log/apache2/audit/*.log
  fields:
    logtype: modsecurity-audit
    service: waf-audit
    environment: production
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "modsecurity-logs-%{+yyyy.MM.dd}"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true