version: '3.8'

services:
  # ModSecurity avec Apache
  modsecurity-apache:
    image: ${MODSECURITY_IMAGE:-owasp/modsecurity:3.0.12-apache}
    container_name: ${MODSECURITY_CONTAINER_NAME:-modsecurity-waf}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./modsecurity-config:/etc/modsecurity.d:ro
      - ./apache-config:/etc/apache2/sites-available:ro
      - ./logs:/var/log/apache2
      - ./ssl:/etc/ssl/certs:ro
    environment:
      - MODSEC_RULE_ENGINE=${MODSEC_RULE_ENGINE:-On}
      - MODSEC_REQ_BODY_ACCESS=${MODSEC_REQ_BODY_ACCESS:-On}
      - MODSEC_REQ_BODY_LIMIT=${MODSEC_REQ_BODY_LIMIT:-13107200}
      - MODSEC_REQ_BODY_NOFILES_LIMIT=${MODSEC_REQ_BODY_NOFILES_LIMIT:-131072}
      - MODSEC_RESP_BODY_ACCESS=${MODSEC_RESP_BODY_ACCESS:-On}
      - MODSEC_RESP_BODY_LIMIT=${MODSEC_RESP_BODY_LIMIT:-524288}
      - BACKEND_HOST=${WEBAPP_SERVICE_NAME:-webapp}
      - BACKEND_PORT=${WEBAPP_INTERNAL_PORT:-80}
      - SERVER_NAME=${SERVER_NAME:-modsecurity.local}
    depends_on:
      - webapp
    dns:
      - 192.168.15.3
    networks:
      - single-node_default
      - soar-network
    restart: ${RESTART_POLICY:-unless-stopped}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/server-status"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.modsecurity.rule=Host(`${SERVER_NAME:-modsecurity.local}`)"

  # Application web de test (DVWA)
  webapp:
    image: ${WEBAPP_IMAGE:-vulnerables/web-dvwa}
    container_name: ${WEBAPP_CONTAINER_NAME:-dvwa-app}
    ports:
      - "${WEBAPP_PORT:-8080}:80"
    environment:
      - MYSQL_HOSTNAME=${DB_HOST:-mysql-db}
      - MYSQL_DATABASE=${DB_NAME:-dvwa}
      - MYSQL_USERNAME=${DB_USER:-dvwa}
      - MYSQL_PASSWORD=${DB_PASSWORD:-p@ssw0rd}
      - DVWA_DIFFICULTY=${DVWA_DIFFICULTY:-low}
      - DVWA_RECAPTCHA_PUBLIC_KEY=${DVWA_RECAPTCHA_PUBLIC_KEY:-}
      - DVWA_RECAPTCHA_PRIVATE_KEY=${DVWA_RECAPTCHA_PRIVATE_KEY:-}
    depends_on:
      mysql-db:
        condition: service_healthy
    dns:
      - 192.168.15.3
    networks:
      - single-node_default
      - soar-network
    restart: ${RESTART_POLICY:-unless-stopped}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Base de données MySQL pour DVWA
  mysql-db:
    image: ${DB_IMAGE:-mysql:8.0}
    container_name: ${DB_CONTAINER_NAME:-mysql-dvwa}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_NAME:-dvwa}
      - MYSQL_USER=${DB_USER:-dvwa}
      - MYSQL_PASSWORD=${DB_PASSWORD:-p@ssw0rd}
      - MYSQL_CHARACTER_SET_SERVER=${DB_CHARSET:-utf8mb4}
      - MYSQL_COLLATION_SERVER=${DB_COLLATION:-utf8mb4_unicode_ci}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d:ro
    networks:
      - soar-network
    restart: ${RESTART_POLICY:-unless-stopped}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password

  # Agent Wazuh pour ModSecurity
  wazuh-agent:
    image: ${WAZUH_AGENT_IMAGE:-wazuh/wazuh-agent:4.7.2}
    container_name: ${WAZUH_AGENT_CONTAINER_NAME:-wazuh-agent-modsec}
    environment:
      - WAZUH_MANAGER=${WAZUH_MANAGER_IP}
      - WAZUH_MANAGER_PORT=${WAZUH_MANAGER_PORT:-1514}
      - WAZUH_PROTOCOL=${WAZUH_PROTOCOL:-tcp}
      - WAZUH_REGISTRATION_SERVER=${WAZUH_REGISTRATION_SERVER:-${WAZUH_MANAGER_IP}}
      - WAZUH_REGISTRATION_PORT=${WAZUH_REGISTRATION_PORT:-1515}
      - WAZUH_AGENT_GROUP=${WAZUH_AGENT_GROUP:-modsecurity}
      - WAZUH_AGENT_NAME=${WAZUH_AGENT_NAME:-modsecurity-waf}
      - WAZUH_KEEP_ALIVE_INTERVAL=${WAZUH_KEEP_ALIVE_INTERVAL:-60}
      - WAZUH_TIME_RECONNECT=${WAZUH_TIME_RECONNECT:-60}
      - WAZUH_AUTO_RESTART=${WAZUH_AUTO_RESTART:-yes}
    volumes:
      - ./wazuh-config/ossec.conf:/var/ossec/etc/ossec.conf:ro
      - ./logs:/var/log/apache2:ro
      - wazuh-agent-data:/var/ossec/var
      - ./scripts:/scripts:ro
    networks:
      - single-node_default
      - soar-network
    restart: ${RESTART_POLICY:-unless-stopped}
    dns:
      - 192.168.15.3
    depends_on:
      - modsecurity-apache
    healthcheck:
      test: ["CMD", "/var/ossec/bin/wazuh-control", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Processeur de logs et webhook forwarder
  log-processor:
    build:
      context: ./scripts
      dockerfile: Dockerfile.log-processor
    container_name: ${LOG_PROCESSOR_CONTAINER_NAME:-log-processor}
    environment:
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - WAZUH_MANAGER_API=${WAZUH_MANAGER_API}
      - WAZUH_API_USER=${WAZUH_API_USER:-wazuh}
      - WAZUH_API_PASSWORD=${WAZUH_API_PASSWORD:-wazuh}
      - THEHIVE_URL=${THEHIVE_URL}
      - THEHIVE_API_KEY=${THEHIVE_API_KEY}
      - CORTEX_URL=${CORTEX_URL}
      - CORTEX_API_KEY=${CORTEX_API_KEY}
      - MISP_URL=${MISP_URL}
      - MISP_API_KEY=${MISP_API_KEY}
      - ALERT_THROTTLE_MINUTES=${ALERT_THROTTLE_MINUTES:-5}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ANALYST_NAME=${ANALYST_NAME:-Med10S}
      - ENVIRONMENT=${ENVIRONMENT:-SOAR-Lab}
    volumes:
      - ./scripts:/scripts:ro
      - ./logs:/var/log/apache2:rw
      - ./monitoring:/monitoring:rw
      - log-processor-data:/data
    networks:
      - single-node_default
      - soar-network
    restart: ${RESTART_POLICY:-unless-stopped}
    dns:
      - 192.168.15.3
    depends_on:
      - modsecurity-apache
    healthcheck:
      test: ["CMD", "pgrep", "-f", "log-processor.sh"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Service de monitoring et healthcheck
  monitoring:
    image: ${MONITORING_IMAGE:-alpine:latest}
    container_name: ${MONITORING_CONTAINER_NAME:-soar-monitoring}
    environment:
      - MONITORING_INTERVAL=${MONITORING_INTERVAL:-60}
      - ALERT_EMAIL=${ALERT_EMAIL}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - ./monitoring:/monitoring:ro
      - ./logs:/var/log/apache2:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    dns:
      - 192.168.15.3
    networks:
      - single-node_default
      - soar-network
    restart: ${RESTART_POLICY:-unless-stopped}
    command: /bin/sh -c "apk add --no-cache curl docker-cli python3 py3-pip && pip3 install requests && /monitoring/healthcheck.sh"

volumes:
  mysql-data:
    driver: local
    name: ${PROJECT_NAME:-modsecurity-soar}_mysql-data
  wazuh-agent-data:
    driver: local
    name: ${PROJECT_NAME:-modsecurity-soar}_wazuh-data
  log-processor-data:
    driver: local
    name: ${PROJECT_NAME:-modsecurity-soar}_log-processor-data

networks:
  single-node_default:
    external: true
  soar-network:
    driver: bridge
    name: ${PROJECT_NAME:-modsecurity-soar}_network
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET:-172.20.0.0/16}